### ISSUE TITLE
Improve docs for use-cases where plugin is not found

### ISSUE THREAD

**Issue by lewisdonovan** [awslabs/amplify-video#294]
Not sure if it's just my setup (Mac, Zsh, Node installed via Homebrew), but after following the installation instructions and running `amplify video add` I got an error message saying `The Amplify CLI can NOT find command:  video add`. 

I had to manually add the plugin to amplify-cli after installing it. It's not in the docs so I thought I'd add here in case anyone else hit the same issue.

- Remove and reinstall amplify-video.
- After reinstalling, copy the absolute path of the plugin from the terminal output. For me this was `/usr/local/lib/node_modules/amplify-category-video`, but this may be different depending on your setup.
- Run `amplify plugin add` and, when asked, paste the path you copied in the previous step.
- You should now be able to use amplify-video in your project as per the docs.

**Comment by smp** [comment]
Thanks for sharing @lewisdonovan - I've added this to the troubleshooting section of the wiki [here](https://github.com/awslabs/amplify-video/wiki/Troubleshooting)

I'm going to close this ticket for now. If we get to the bottom of the issue and it turns out to be an issue with the plugin itself, we can revisit a fix.
