### ISSUE TITLE
Create Contributor Guidelines

### ISSUE THREAD

**Issue by smp** [awslabs/amplify-video#30]
**Is your feature request related to a problem? Please describe.**
People want to contribute to amplify video, but we can't solicit contributions if we don't help them understand the amplify video project and the guidelines for contribution.

**Describe the solution you'd like**
something like [this](https://github.com/aws-amplify/amplify-js/blob/master/CONTRIBUTING.md)

- a description of the codebase, major files and how the plug-in really works
- an outline of the code standards - tab/spaces, etc.
- where to get in touch or participate in design discussion - chat room? email? etc

**Comment by wizage** [comment]
Here is a rough draft:

# Contributor Guidelines

## Bugs
Bug reports and feature suggestions are welcome. When filing a bug, try to include as much information as you can. Details like these are incredibly useful:

- A reproducible test case or series of steps
- The date/commit of the code you're running
- Any modifications you've made relevant to the bug
- Anything unusual about your environment or deployment

## Pull Requests

Pull requests are welcome!

You should open an issue to discuss your pull request, unless it's a trivial change. It's best to ensure that your proposed change would be accepted so that you don't waste your own time. If you would like to implement support for a significant feature that is not yet available, please talk to us beforehand to avoid any duplication of effort.

Pull requests should generally be opened against **master**.

Eslint should always be run before submitting new pull requests by running `npm run lint-fix`. This should correct any naming conventions and covert spaces/tabs to the preferred defaults.

 ## Understanding the codebase

The codebase folder structure maps to something below:
### root
./index.js
-> Contains the callback functions for amplify for pre/post push.
./amplify-plugin.json
-> Contains all supported plugin commands
### provider-utils
./provider-utils/supported-services.json
-> Defines workflows that are supported by amplify video. Required files are:
- `alias` : What shows up in the question
- `serviceWalkthroughFilename` : What asks the questions for that specific service
- `cfnFilename` : The root template for the service
- `stackFolder` : Contains supporting templates for the service
- `defaultValuesFilename` : Contains default answers to the questions asked in `serviceWalkthroughFilename`
- `provider` : Define what provider you want to use. This maps to the containing folder for the rest of the files. (Right now the Amplify CLI only supports CloudFormation)

#### awscloudformation
./provider-utils/awscloudformation/index.js
-> This file takes the info passed from the servicewalkthrough file and executes it. This file shouldn't be changed that often.

./provider-utils/awscloudformation/utils/
-> Contains all functions that are shared between all video services with respect to CloudFormation

./provider-utils/awscloudformation/service-walkthroughs/
-> Contains the service walkthrough file that is defined in the `supported-services.json`. These files are what asks the questions about what we are creating.

./provider-utils/awscloudformation/obs-templates/
-> Don't worry about this. Just the template for amplify video livestream to configure OBS

./provider-utils/awscloudformation/default-values/
-> Place your defaults value file here that you defined above in the supported-services.json

./provider-utils/awscloudformation/cloudformation-templates/
-> Place your root template here and your folder for your nested stack. You will notice that the templates that already exist for the root stack are .ejs files. EJS allows us to dynamically compile the CloudFormation to add or remove features and passing parameters generated from the CLI. Any folders inside of the nested stack folder will be zipped up and given the same name in .zip on pre push.

### commands
./commands/video.js
-> Contains the help view for amplify video. Any new commands should show up here.

./commands/video/
-> Contains all supported commands defined in the amplify-plugin.json

**Comment by wizage** [comment]
Need to merge with these guidelines:
https://github.com/awslabs/unicornflix/blob/master/CONTRIBUTING.md
