### ISSUE TITLE
Moving away from system templates to Amplify video templates

### ISSUE THREAD

**Issue by wizage** [awslabs/amplify-video#34]
**Is your feature request related to a problem? Please describe.**
Create custom templates for Amplify video to move away from the system templates.

**Describe the solution you'd like**
Put any templates you want inside a templates folder (location to be provided). The name should be human readable and the id should contain "amplify-video-".

To templates are required to finish:
- "Video" ( Specs to be determined by @smp )
- "Video with Thumbnails" ( Should copy video but add thumbnails )

Related to #4

**Comment by wizage** [comment]
This is ready now! Place any template in the Templates folder found [here](https://github.com/awslabs/amplify-video/tree/master/provider-utils/awscloudformation/templates).

Thinks to note:

- Description is used as the "English" name for the prompts
- Name is used for internal variable setting, and must contain `Amplify_Video_`

All templates that do not adhere to this will be denied.

**Comment by smp** [comment]
staging a change with the following template settings...


- Name: Amplify_Video_Basic_HLS
- Description: Basic HLS Encoding
- Category: Amplify-Video
- QVBR, Single Pass - should keep us in basic tier pricing
- 30fps max, need to set fps for inputs instead of follow because hls segmentation needs a divisible framerate for GOP.
- 5 renditions total. One is audio-only, top resolution follows source, ranges from 3mbps down to 325kbps
- using $dt$ modifier on each segment to avoid accidental media overwrites. We will still overwrite the manifest names if the same file is uploaded into amplify video.


@wizage do you want to remove the other templates in this change too?
