### ISSUE TITLE
Just audio support?

### ISSUE THREAD

**Issue by subhendukundu** [awslabs/amplify-video#94]
I would like to stream just audio like a live FM. Would it possible with this plugin? Like amplify-audio?
If not possible with the current version, can we expect one anytime soon?
Is there anyway I can achieve audio streaming much simplier or easier way?

Thanks.

**Comment by axptwig** [comment]
Hey @subhendukundu,

You can do this but you will need to make some changes to the existing code. You need to do 2 things.

1. Create a new S3 event listening for .mp3 files which gets sent to the inputLambda function
1. Reference another Mediaconvert Job Template configured with a filegroup output. (you can do this by referencing the template when configuring the amplify resource)

Here are the steps you can take in order to achieve an audio pipeline.
1. Navigate to the Mediaconvert service page and select job templates.
1. You will need a to create a new job template. Reference the below doc link on how to create audio only outputs 
    1. https://docs.aws.amazon.com/mediaconvert/latest/ug/setting-up-audio-only.html
    1. If you need help making this I can show you an example of the JSON i have used before for mp3 to HLS transcoding.
1. Initialize an amplify environment with `amplify init`
1. Next, `amplify video add` and select Video on Demand.
1. For the question `Select a system-provided encoding template, specify an already-created template name` choose `Bring your own template` and specify the name of the audio MediaConvert template you created previously. 
1. Continue configuring the resource as you would normally.
1. Once the prompt exits, check `amplify status` to see that your resource is configured to be created.
1. Navigate to `/amplify/backend/video/audio/vod-helpers/LambdaFunctions/SetupTriggerLambda/index.js` and change the listner for 'mp4' to 'mp3' or whatever your input container is and save the file. 
    1. You can view the list of supported containers here: https://docs.aws.amazon.com/mediaconvert/latest/ug/supported-codecs-containers-audio-only.html
1. run `amplify push` and you should be all set.

**Comment by axptwig** [comment]
*Note* you must supply a valid s3 bucket name before importing this template into mediaconvert.

```
{
  "Name": "audio_template",
  "Settings": {
    "OutputGroups": [
      {
        "Name": "Apple HLS",
        "Outputs": [
          {
            "ContainerSettings": {
              "Container": "M3U8",
              "M3u8Settings": {
                "AudioFramesPerPes": 4,
                "PcrControl": "PCR_EVERY_PES_PACKET",
                "PmtPid": 480,
                "PrivateMetadataPid": 503,
                "ProgramNumber": 1,
                "PatInterval": 0,
                "PmtInterval": 0,
                "Scte35Source": "NONE",
                "NielsenId3": "NONE",
                "TimedMetadata": "NONE",
                "VideoPid": 481,
                "AudioPids": [
                  482,
                  483,
                  484,
                  485,
                  486,
                  487,
                  488,
                  489,
                  490,
                  491,
                  492
                ]
              }
            },
            "AudioDescriptions": [
              {
                "AudioTypeControl": "FOLLOW_INPUT",
                "AudioSourceName": "Audio Selector 1",
                "CodecSettings": {
                  "Codec": "AAC",
                  "AacSettings": {
                    "AudioDescriptionBroadcasterMix": "NORMAL",
                    "Bitrate": 96000,
                    "RateControlMode": "CBR",
                    "CodecProfile": "LC",
                    "CodingMode": "CODING_MODE_2_0",
                    "RawFormat": "NONE",
                    "SampleRate": 48000,
                    "Specification": "MPEG4"
                  }
                },
                "LanguageCodeControl": "FOLLOW_INPUT"
              }
            ],
            "OutputSettings": {
              "HlsSettings": {
                "AudioGroupId": "program_audio",
                "AudioOnlyContainer": "AUTOMATIC",
                "IFrameOnlyManifest": "EXCLUDE"
              }
            },
            "NameModifier": "_audio"
          }
        ],
        "OutputGroupSettings": {
          "Type": "HLS_GROUP_SETTINGS",
          "HlsGroupSettings": {
            "ManifestDurationFormat": "INTEGER",
            "SegmentLength": 10,
            "TimedMetadataId3Period": 10,
            "CaptionLanguageSetting": "OMIT",
            "Destination": "s3://**YOUR-S3-BUCKET**/mp3/",
            "TimedMetadataId3Frame": "PRIV",
            "CodecSpecification": "RFC_4281",
            "OutputSelection": "MANIFESTS_AND_SEGMENTS",
            "ProgramDateTimePeriod": 600,
            "MinSegmentLength": 0,
            "MinFinalSegmentLength": 0,
            "DirectoryStructure": "SINGLE_DIRECTORY",
            "ProgramDateTime": "EXCLUDE",
            "SegmentControl": "SEGMENTED_FILES",
            "ManifestCompression": "NONE",
            "ClientCache": "ENABLED",
            "StreamInfResolution": "INCLUDE"
          }
        }
      }
    ],
    "AdAvailOffset": 0,
    "Inputs": [
      {
        "AudioSelectors": {
          "Audio Selector 1": {
            "Offset": 0,
            "DefaultSelection": "DEFAULT",
            "ProgramSelection": 1
          }
        },
        "FilterEnable": "AUTO",
        "PsiControl": "USE_PSI",
        "FilterStrength": 0,
        "DeblockFilter": "DISABLED",
        "DenoiseFilter": "DISABLED",
        "TimecodeSource": "EMBEDDED"
      }
    ]
  },
  "AccelerationSettings": {
    "Mode": "DISABLED"
  },
  "StatusUpdateInterval": "SECONDS_60",
  "Priority": 0,
  "HopDestinations": []
}
```

**Comment by subhendukundu** [comment]
Thank you so much for the explanations, it does make sense. I will try this out.
One more quick question Would be possible to make Real-Time communication? What I mean is, like if someone else wants to join to the live show, would that be possible?
Something like, rtc network protocol?

**Comment by axptwig** [comment]
Currently WebRTC is not a supported protocol. For that you need to use something like Kinesis video with WebRTC. 

https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/what-is-kvswebrtc.html
